# Generated by Django 4.1.3 on 2022-11-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20)),
                ('low', models.IntegerField(default=0)),
                ('high', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
            ],
        ),
    ]
