# Generated by Django 4.1.3 on 2022-11-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0003_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
