# Generated by Django 4.1.3 on 2022-11-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0004_alter_recipient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='currentPrice',
            field=models.FloatField(default=1.0),
        ),
    ]
